# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=120)),
                ('phone_number_2', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('family_size', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('max_edu_level', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('land_area', models.FloatField()),
                ('planted_crops', models.CharField(blank=True, max_length=120)),
                ('source_of_labour', models.CharField(blank=True, max_length=120)),
                ('extension_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=120)),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('max_edu_level', models.CharField(blank=True, max_length=120)),
                ('residence_state', models.CharField(blank=True, max_length=120)),
                ('lga', models.CharField(blank=True, max_length=120)),
                ('degree', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
