# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(blank=True, max_length=120)),
                ('fertility_class', models.CharField(blank=True, max_length=120)),
                ('nutrient', models.CharField(blank=True, max_length=120)),
                ('nutrient_rate', models.CharField(blank=True, max_length=120)),
                ('zone', models.CharField(blank=True, max_length=200)),
                ('fertilizer_rate', models.TextField(blank=True)),
                ('application', models.TextField(blank=True)),
            ],
        ),
    ]
