# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_soilrecommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('farm_size', models.FloatField(blank=True)),
                ('last_fertilizer_app', models.DateField()),
                ('soil_tillage', models.CharField(choices=[('conventional', 'Conventional Tillage'), ('conservation', 'Conservation Tillage'), ('no-till', 'No Tillage')], max_length=120)),
                ('planted_crops', models.TextField()),
                ('sample_amount', models.IntegerField()),
                ('sample_size', models.FloatField()),
                ('soil_depth', models.CharField(choices=[('0_2', '0-2'), ('2_4', '2-4'), ('4_6', '4-6'), ('6_8', '6-8')], max_length=4)),
                ('soil_type', models.CharField(blank=True, choices=[('sandy', 'Sandy Soil'), ('loamy', 'Loamy Soil'), ('laterite', 'Laterite Soil'), ('alluvial', 'Alluvial Soil')], max_length=120)),
                ('soil_ph', models.FloatField()),
                ('nutrient_ratings', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
