# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180606_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='annual_production_volume',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='farmer',
            name='town',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='annual_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='max_edu_level',
            field=models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Quaranica'), ('3', 'Primary'), ('4', 'Secondary'), ('5', 'Tertiary')], max_length=120),
        ),
    ]
