# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 23:51
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180610_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='annual_production_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmpicture',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_pics', to='server.Farmer'),
        ),
    ]
