# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180703_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltestdata',
            name='soil_depth',
            field=models.CharField(choices=[('0_15', '0-15'), ('15.1_30', '15.1-30'), ('30.1_45', '30.1-45'), ('_45', '>45')], max_length=10),
        ),
    ]
