# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180703_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltestdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 3, 23, 54, 13, 346101, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
