# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_soiltestdata_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltestdata',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to='server.Farmer'),
        ),
    ]
