# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20180704_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soiltestdata',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay Soil'), ('sand', 'Sandy Soil'), ('loam', 'Loamy Soil'), ('silt', 'Silt'), ('sandy_clay', 'Sandy Clay'), ('silty_clay', 'Silty Clay'), ('clay_loam', 'Clay Loam'), ('loamy_sand', 'Loamy Sand'), ('sandy_loam', 'Sandy Loam'), ('silt_loam', 'Silt Loam'), ('silt_clay_loam', 'Silt Clay Loam'), ('sandy_clay_loam', 'Sandy Clay Loam')], max_length=120),
        ),
    ]
