# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20180716_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='town',
        ),
        migrations.AddField(
            model_name='farmer',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Lga'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.State'),
        ),
    ]
