# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20180721_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='town',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
